/*
 * CodeStyle.H
 *
 *  Created on: Nov 17, 2012
 *      Author: Eric
 */

#ifndef CODESTYLE_H_
#define CODESTYLE_H_

//TODO Remove this and place asserts in all relevant functions

class CodeStyle {
public:
	CodeStyle();
	virtual ~CodeStyle();

	/*
	 * Function description
	 */
	void exampleFunction(int anExampleInput) {
		//Variable declaration

		int j, k, l = 0; //loop counters
		int a = 7;
		int b = 21;	//age

		//Comment
		//another comment

		//Function body

		//Loop, what do you do?
		for (int i = 0; i < 10; i++) {
			//Do stuff
		}

		//Return if applicable

		//Description of return value
	}

};

#endif /* CODESTYLE_H_ */
